import {
  Award,
  Baby,
  Briefcase,
  Building2,
  Car,
  CircleEllipsis,
  Droplets,
  Ellipsis,
  Gift,
  Globe,
  GraduationCap,
  HandCoins,
  HeartPulse,
  Home,
  Lamp,
  Laptop,
  PawPrint,
  PiggyBank,
  Plane,
  Receipt,
  Shield,
  Shirt,
  ShoppingBasket,
  Smartphone,
  SunMedium,
  Tag,
  Ticket,
  TrendingUp,
  UserRound,
  Users,
  Utensils,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { CategoryKey } from "@/lib/budget/types";

const ICONS: Record<CategoryKey, LucideIcon> = {
  catFood: Utensils,
  catGroceries: ShoppingBasket,
  catTransport: Car,
  catHousing: Home,
  catElectricity: Zap,
  catWater: Droplets,
  catPhone: Smartphone,
  catHealth: HeartPulse,
  catEducation: GraduationCap,
  catClothes: Shirt,
  catHousehold: Lamp,
  catChildren: Baby,
  catFamily: Users,
  catFun: Ticket,
  catPersonal: UserRound,
  catInsurance: Shield,
  catDebt: HandCoins,
  catSavings: PiggyBank,
  catGifts: Gift,
  catFestivals: SunMedium,
  catTravel: Plane,
  catPets: PawPrint,
  catTaxes: Receipt,
  catRepairs: Wrench,
  catOther: Ellipsis,
  catSalary: Wallet,
  catBusiness: Briefcase,
  catFreelance: Laptop,
  catRentIn: Building2,
  catInvest: TrendingUp,
  catRemit: Globe,
  catBonus: Award,
  catGiftIn: Gift,
  catSales: Tag,
  catOtherIn: CircleEllipsis,
};

export function CategoryGlyph({
  nameKey,
  className,
}: {
  nameKey: CategoryKey | null;
  className?: string;
}) {
  const Icon = (nameKey && ICONS[nameKey]) || Tag;
  return <Icon className={className} aria-hidden strokeWidth={1.75} />;
}
